# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('menu_name', models.CharField(max_length=80, verbose_name='Название в меню')),
                ('menu_position', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Позиция в меню')),
                ('content', redactor.fields.RedactorField(verbose_name='Контент')),
                ('keywords', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Сраницу',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
