# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu_position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция в меню'),
        ),
    ]
