# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_auto_20170406_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('content', redactor.fields.RedactorField(verbose_name='Контент')),
                ('slide_position', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Позиция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображене')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_position',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Позиция в меню'),
        ),
    ]
