# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_auto_20170407_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=128, verbose_name='Имя в меню')),
                ('url', models.URLField(verbose_name='Ссылка настраницу')),
                ('menu_position', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Позиция в меню')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
