# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('experience', models.CharField(max_length=200, verbose_name='Стаж')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('content', redactor.fields.RedactorField(max_length=10000, verbose_name='Контент')),
                ('keywords', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
