# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 10:30
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врача', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Контент'),
        ),
    ]
