# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20170410_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='special',
        ),
        migrations.AddField(
            model_name='doctor',
            name='special',
            field=models.ManyToManyField(to='doctor.Specialization'),
        ),
    ]
